---
title: "Untitled"
author: "Itamar Caspi"
date: "21 10 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(RcppAlgos)
```

```{r}
df_raw <- readxl::read_xlsx(path = "data/data_20102020.xlsx")
  
df <- 
  df_raw %>% 
  select(city_desc, new_verified_last_week, total_pop) %>% 
  rename(
    city = city_desc,
    cases = new_verified_last_week,
    pop = total_pop
  ) %>% 
  head(4)
```


```{r}
total_pop   <- 8935705
numOfCities <- 3
maxPop      <- 0.04 * total_pop

# Taking all combinations of prices and points
casesCombs <- RcppAlgos::comboGeneral(df$cases, numOfCities)
popCombs   <- RcppAlgos::comboGeneral(df$pop, numOfCities)
cityCombs  <- RcppAlgos::comboGeneral(df$city, numOfCities)

# Computing best choice
magicIndex <- which.max(rowSums(casesCombs[rowSums(popCombs) < maxPop,])) # gives the corresponding index


results <- tibble(
  "city"  = cityCombs[magicIndex,],
  "cases" = casesCombs[magicIndex,],
  "pop"   = popCombs[magicIndex,]
)

results

results %>% 
  dplyr::summarise(pop = sum(pop/total_pop))
```

